// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcnczdormgfpvgkgxmls.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjbmN6ZG9ybWdmcHZna2d4bWxzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ1NDE4NTQsImV4cCI6MjA5MDExNzg1NH0.23W9c7gBvvnF1oLP5fl92GnD_JH1am8ETRy6gYHWn9g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});