// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wljqdaxnrapwfineiuvu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndsanFkYXhucmFwd2ZpbmVpdXZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM5MjA1OTcsImV4cCI6MjA4OTQ5NjU5N30.Yi9JA0UVRKqMsRp3zsugzowPE54CmfBR35lPuC-P8Pg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});